In [37]:
import pandas as pd
import numpy as np

from nltk.tokenize import word_tokenize
from nltk.util import ngrams

In [45]:
df1 = pd.read_csv('cleaned_data_very.csv')
df1=df1.dropna()
df1

            class                                             tweets
0      figurative  aware dirty step get money staylight staywhite...
1      figurative            sarcasm people understand diy artattack
2      figurative  iminworkjeremy medsingle dailymail readers sen...
3      figurative                wilw get feeling like games sarcasm
4      figurative  teacherarthurg rweingarten probably missed tex...
...           ...                                                ...
66303     sarcasm  photo image via heart childhood cool funny sar...
66304     sarcasm  never knew better put universe lol maybe date ...
66305     sarcasm  hey wanted say thanks puberty letting apart it...
66306     sarcasm  sure coverage like fox news special hidden har...
66307     sarcasm                 skeyno16 u13 believe see p sarcasm

[66307 rows x 2 columns]

In [46]:
df1_tweet = df1['tweets'].apply(word_tokenize)
df1_tweet

0        [aware, dirty, step, get, money, staylight, st...
1            [sarcasm, people, understand, diy, artattack]
2        [iminworkjeremy, medsingle, dailymail, readers...
3               [wilw, get, feeling, like, games, sarcasm]
4        [teacherarthurg, rweingarten, probably, missed...
                               ...
66303    [photo, image, via, heart, childhood, cool, fu...
66304    [never, knew, better, put, universe, lol, mayb...
66305    [hey, wanted, say, thanks, puberty, letting, a...
66306    [sure, coverage, like, fox, news, special, hid...
66307            [skeyno16, u13, believe, see, p, sarcasm]
Name: tweets, Length: 66307, dtype: object

In [47]:
df1 = pd.DataFrame({'class':df1['class'], 'tweets': df1_tweet})
df1

            class                                             tweets
0      figurative  [aware, dirty, step, get, money, staylight, st...
1      figurative      [sarcasm, people, understand, diy, artattack]
2      figurative  [iminworkjeremy, medsingle, dailymail, readers...
3      figurative         [wilw, get, feeling, like, games, sarcasm]
4      figurative  [teacherarthurg, rweingarten, probably, missed...
...           ...                                                ...
66303     sarcasm  [photo, image, via, heart, childhood, cool, fu...
66304     sarcasm  [never, knew, better, put, universe, lol, mayb...
66305     sarcasm  [hey, wanted, say, thanks, puberty, letting, a...
66306     sarcasm  [sure, coverage, like, fox, news, special, hid...
66307     sarcasm          [skeyno16, u13, believe, see, p, sarcasm]

[66307 rows x 2 columns]

In [51]:
# Function to generate n-grams
def generate_ngrams(tokens, n):
    return [' '.join(gram) for gram in list(ngrams(tokens, n))]

# Generate unigrams, bigrams, and trigrams for each row
df1['unigrams'] = df1['tweets'].apply(lambda tweet: generate_ngrams(tweet, 1))
df1['bigrams'] = df1['tweets'].apply(lambda tweet: generate_ngrams(tweet, 2))
df1['trigrams'] = df1['tweets'].apply(lambda tweet: generate_ngrams(tweet, 3))

df1.head()

,class,tweets,unigrams,bigrams,trigrams
0,figurative,"[aware, dirty, step, get, money, staylight, st...","[aware, dirty, step, get, money, staylight, st...","[aware dirty, dirty step, step get, get money,...","[aware dirty step, dirty step get, step get mo..."
1,figurative,"[sarcasm, people, understand, diy, artattack]","[sarcasm, people, understand, diy, artattack]","[sarcasm people, people understand, understand...","[sarcasm people understand, people understand ..."
2,figurative,"[iminworkjeremy, medsingle, dailymail, readers...","[iminworkjeremy, medsingle, dailymail, readers...","[iminworkjeremy medsingle, medsingle dailymail...","[iminworkjeremy medsingle dailymail, medsingle..."
3,figurative,"[wilw, get, feeling, like, games, sarcasm]","[wilw, get, feeling, like, games, sarcasm]","[wilw get, get feeling, feeling like, like gam...","[wilw get feeling, get feeling like, feeling l..."
4,figurative,"[teacherarthurg, rweingarten, probably, missed...","[teacherarthurg, rweingarten, probably, missed...","[teacherarthurg rweingarten, rweingarten proba...","[teacherarthurg rweingarten probably, rweingar..."

In [53]:
df1['four_grams'] = df1['tweets'].apply(lambda tweet: generate_ngrams(tweet, 4))
df1

,class,tweets,unigrams,bigrams,trigrams,four_grams
0,figurative,"[aware, dirty, step, get, money, staylight, st...","[aware, dirty, step, get, money, staylight, st...","[aware dirty, dirty step, step get, get money,...","[aware dirty step, dirty step get, step get mo...","[aware dirty step get, dirty step get money, s..."
1,figurative,"[sarcasm, people, understand, diy, artattack]","[sarcasm, people, understand, diy, artattack]","[sarcasm people, people understand, understand...","[sarcasm people understand, people understand ...","[sarcasm people understand diy, people underst..."
2,figurative,"[iminworkjeremy, medsingle, dailymail, readers...","[iminworkjeremy, medsingle, dailymail, readers...","[iminworkjeremy medsingle, medsingle dailymail...","[iminworkjeremy medsingle dailymail, medsingle...","[iminworkjeremy medsingle dailymail readers, m..."
3,figurative,"[wilw, get, feeling, like, games, sarcasm]","[wilw, get, feeling, like, games, sarcasm]","[wilw get, get feeling, feeling like, like gam...","[wilw get feeling, get feeling like, feeling l...","[wilw get feeling like, get feeling like games..."
4,figurative,"[teacherarthurg, rweingarten, probably, missed...","[teacherarthurg, rweingarten, probably, missed...","[teacherarthurg rweingarten, rweingarten proba...","[teacherarthurg rweingarten probably, rweingar...","[teacherarthurg rweingarten probably missed, r..."
...,...,...,...,...,...,...
66303,sarcasm,"[photo, image, via, heart, childhood, cool, fu...","[photo, image, via, heart, childhood, cool, fu...","[photo image, image via, via heart, heart chil...","[photo image via, image via heart, via heart c...","[photo image via heart, image via heart childh..."
66304,sarcasm,"[never, knew, better, put, universe, lol, mayb...","[never, knew, better, put, universe, lol, mayb...","[never knew, knew better, better put, put univ...","[never knew better, knew better put, better pu...","[never knew better put, knew better put univer..."
66305,sarcasm,"[hey, wanted, say, thanks, puberty, letting, a...","[hey, wanted, say, thanks, puberty, letting, a...","[hey wanted, wanted say, say thanks, thanks pu...","[hey wanted say, wanted say thanks, say thanks...","[hey wanted say thanks, wanted say thanks pube..."
66306,sarcasm,"[sure, coverage, like, fox, news, special, hid...","[sure, coverage, like, fox, news, special, hid...","[sure coverage, coverage like, like fox, fox n...","[sure coverage like, coverage like fox, like f...","[sure coverage like fox, coverage like fox new..."
66307,sarcasm,"[skeyno16, u13, believe, see, p, sarcasm]","[skeyno16, u13, believe, see, p, sarcasm]","[skeyno16 u13, u13 believe, believe see, see p...","[skeyno16 u13 believe, u13 believe see, believ...","[skeyno16 u13 believe see, u13 believe see p, ..."

In [55]:
df1['bigrams'].iloc[0]

['aware dirty',
 'dirty step',
 'step get',
 'get money',
 'money staylight',
 'staylight staywhite',
 'staywhite sarcastic',
 'sarcastic moralneeded']

In [56]:
df1['trigrams'].iloc[0]

['aware dirty step',
 'dirty step get',
 'step get money',
 'get money staylight',
 'money staylight staywhite',
 'staylight staywhite sarcastic',
 'staywhite sarcastic moralneeded']

In [54]:
df1['four_grams'].iloc[0]

['aware dirty step get',
 'dirty step get money',
 'step get money staylight',
 'get money staylight staywhite',
 'money staylight staywhite sarcastic',
 'staylight staywhite sarcastic moralneeded']